title: CT's log
description: > # this means to ignore newlines until "baseurl:"
  @Tian <br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aurea377.github.io" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: 'Tian'
  last_name: 'Cao'
  cv: '//kaptn.ru'
  avatar: '/images/avatar.png'
  github_username:  Aurea377
  email: tiancao_ct@outlook.com
  #vk_id: id201664979
  #telegram_name: vikapitoshka 
  logo: '/images/logo_ct.png'

# Build settings
markdown: kramdown

permalink: /:categories/:year/:title.html


